---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: secrets
  dataFrom:
    - find:
        path: "SONGLINKER_"
      rewrite:
        - regexp:
            source: "SONGLINKER_(.+)"
            target: "$1"
