---
apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telegram-bot
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: telegram-bot
  serviceName: telegram-bot
  replicas: {{ if .Values.isEnabled }}1{{ else }}0{{ end }}
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      serviceAccountName: bot
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: app
          image: {{ .Values.imageName }}:{{ .Values.appVersion }}
          args:
            - handle-updates
          env:
            - name: ENABLE_TELEMETRY
              value: "true"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: https://api.honeycomb.io
          envFrom:
            - secretRef:
                name: secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
