apiVersion: v1
kind: Secret
metadata:
  name: base
stringData:
  OTEL_EXPORTER_OTLP_TRACES_HEADERS: "x-honeycomb-team={{ .Values.honeycomb.team }}"
  SENTRY_DSN: "{{ .Values.sentry.dsn }}"
  SONGLINK_API_TOKEN: "{{ .Values.apiToken.songlink }}"
