---
apiVersion: v1
kind: Service
metadata:
  name: bot
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bot
spec:
  selector:
    matchLabels:
      app: bot
  serviceName: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          args:
            - handle-updates
          envFrom:
            - secretRef:
                name: secrets
