---
apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telegram-bot
spec:
  selector:
    matchLabels:
      app: telegram-bot
  serviceName: telegram-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          args:
            - handle-updates
          env:
            - name: ENABLE_TELEMETRY
              value: "true"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: https://api.honeycomb.io
          envFrom:
            - secretRef:
                name: base
            - secretRef:
                name: telegram
