name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bullseye
    steps:
      - name: Install Poetry
        run: pip install poetry==1.7.1
      - uses: actions/checkout@v4
      - run: poetry install
      - name: Check coding standards
        run: |
          poetry run ruff check src/
          poetry run black --check src/
          poetry run mypy src/

  integration-test:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    container: python:3.12-slim-bullseye
    steps:
      - name: Install Poetry
        run: pip install poetry==1.7.1
      - uses: actions/checkout@v4
      - run: poetry install
      - name: Run tests
        env:
          SONGLINK_API_TOKEN: ${{ secrets.SONGLINK_API_TOKEN }}
        run: poetry run pytest -m "integration" src/

  unit-test:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bullseye
    steps:
      - name: Install Poetry
        run: pip install poetry==1.7.1
      - uses: actions/checkout@v4
      - run: poetry install
      - name: Run tests
        run: poetry run pytest -m "not integration" src/

  build-container-image:
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'pull_request'
    needs:
      - lint
      - unit-test
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:${{ github.sha }}"

  push-container-image:
    runs-on: ubuntu-latest
    if: success() && github.ref_name == github.event.repository.default_branch
    needs:
      - integration-test
      - lint
      - unit-test
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            APP_VERSION=${{ github.sha }}
          tags: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:${{ github.sha }}"

  deploy:
    runs-on: ubuntu-latest
    needs:
      - push-container-image
    concurrency: production
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - uses: actions/checkout@v4
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
        env:
          HONEYCOMB_API_TOKEN: ${{ secrets.HONEYCOMB_API_TOKEN }}
          IMAGE_NAME: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SONGLINK_API_TOKEN: ${{ secrets.SONGLINK_API_TOKEN }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade bot . --install --namespace=telegram-songlinker-bot --atomic
          kubeconfig: '${{ secrets.KUBECONFIG_RAW }}'

  clean:
    runs-on: ubuntu-latest
    concurrency: cleanup
    continue-on-error: true
    needs: [ deploy ]
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Clean up old app container images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
          package-type: container
          min-versions-to-keep: 10
