name: Workflow
on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.10-slim
    steps:
      - name: Install Poetry
        run: pip install poetry
      - uses: actions/checkout@v3
      - run: poetry install
      - name: Check coding standards
        run: |
          poetry run black --check src/
          poetry run flake8 src/
          poetry run mypy src/

  push_docker:
    runs-on: ubuntu-latest
    needs:
      - lint
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/preparingforexams/telegram-songlinker-bot:${GITHUB_SHA} --build-arg "build=${GITHUB_SHA}" .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/preparingforexams/telegram-songlinker-bot:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: push_docker
    steps:
      - uses: actions/checkout@v3
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SONGLINK_API_TOKEN: ${{ secrets.SONGLINK_API_TOKEN }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade bot . --install --namespace=telegram-songlinker-bot
          kubeconfig: '${{ secrets.KUBECONFIG_RAW }}'
