name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  lint:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v2
    with:
      python-version: '3.12'

  integration-test:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bookworm
    steps:
      - name: Install Poetry
        run: pip install poetry==1.8.4
      - uses: actions/checkout@v4
      - run: poetry install
      - name: Run tests
        env:
          SONGLINK_API_TOKEN: ${{ secrets.SONGLINK_API_TOKEN }}
        run: poetry run pytest -m "integration" src/

  unit-test:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bookworm
    steps:
      - name: Install Poetry
        run: pip install poetry==1.8.4
      - uses: actions/checkout@v4
      - run: poetry install
      - name: Run tests
        run: poetry run pytest -m "not integration" src/

  build-container-image:
    needs:
      - lint
      - unit-test
      - integration-test
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-docker.yml@v3
    with:
      platform: "linux/arm64"
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - build-container-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/clean.yml@v3
