name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  lint:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v1
    with:
      python-version: '3.12'

  integration-test:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bookworm
    steps:
      - name: Install Poetry
        run: pip install poetry==1.8.2
      - uses: actions/checkout@v4
      - run: poetry install
      - name: Run tests
        env:
          SONGLINK_API_TOKEN: ${{ secrets.SONGLINK_API_TOKEN }}
        run: poetry run pytest -m "integration" src/

  unit-test:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bookworm
    steps:
      - name: Install Poetry
        run: pip install poetry==1.8.2
      - uses: actions/checkout@v4
      - run: poetry install
      - name: Run tests
        run: poetry run pytest -m "not integration" src/

  build-container-image:
    needs:
      - lint
      - unit-test
      - integration-test
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-docker.yml@v3
    with:
      platform: "linux/arm64"
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: born-prep
    container: ghcr.io/bjoernpetersen/helm:2.0.1
    needs:
      - build-container-image
    concurrency: production
    if: success() && github.ref_name == github.event.repository.default_branch
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - uses: actions/checkout@v4
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
        env:
          HONEYCOMB_API_TOKEN: ${{ secrets.HONEYCOMB_API_TOKEN }}
          IMAGE_NAME: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SONGLINK_API_TOKEN: ${{ secrets.SONGLINK_API_TOKEN }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      - uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm upgrade bot . --install --namespace=songlinker-bot --atomic
          kubeconfig: '${{ secrets.BORN_KUBECONFIG_RAW }}'

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/clean.yml@v3
