name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

permissions:
  contents: read

jobs:
  required-meta:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v2

  lint:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v5
    with:
      build-tool: uv
      python-version: '3.13'

  integration-test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v5
    with:
      build-tool: uv
      python-version: '3.13'
      tests-selector: integration
    secrets:
      ENVIRONMENT_VARIABLES: |
        SONGLINK_API_TOKEN=${{ secrets.SONGLINK_API_TOKEN }}

  unit-test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v5
    with:
      build-tool: uv
      python-version: '3.13'
      tests-selector: not integration

  build-container-image:
    needs:
      - lint
      - unit-test
      - integration-test
    uses: preparingforexams/actions-container/.github/workflows/build-dual-image-buildah.yml@v7
    permissions:
      contents: read
      packages: write
    with:
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  post-build-container-image:
    runs-on: ubuntu-24.04
    if: "!cancelled() && github.event_name == 'pull_request'"
    needs: build-container-image
    steps:
      - run: |
          if [ "true" == "${{ contains(needs.*.result, 'failure') }}" ]
          then
            echo "A required job failed"
            exit 1
          else
            echo "All required jobs passed"
          fi

  deploy:
    runs-on: ubuntu-24.04
    if: github.ref_name == github.event.repository.default_branch
    permissions:
      contents: write
    needs:
      - build-container-image
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: preparingforexams/actions-container/.github/workflows/clean.yml@v7
    permissions:
      packages: write
