name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  lint:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v2
    with:
      build-tool: uv
      python-version: '3.13'

  integration-test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v2
    with:
      build-tool: uv
      python-version: '3.13'
      tests-selector: integration
    secrets:
      ENVIRONMENT_VARIABLES: |
        SONGLINK_API_TOKEN=${{ secrets.SONGLINK_API_TOKEN }}

  unit-test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v2
    with:
      build-tool: uv
      python-version: '3.13'
      tests-selector: not integration

  build-container-image:
    needs:
      - lint
      - unit-test
      - integration-test
    uses: preparingforexams/actions-container/.github/workflows/build-image-kaniko.yml@v3
    with:
      runner-name-build: warp-ubuntu-latest-arm64-2x
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - build-container-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: preparingforexams/actions-container/.github/workflows/clean.yml@v4
